### ISSUE TITLE
Convert event handler module to python module

### ISSUE THREAD

**Issue by dekarrin** [moe-serifu-circle/moe-serifu-agent#52]
The event handler module, located in src/event/handler.{hpp,cpp}, is responsible for setting up synchronization primitives and allowing handlers to indicate when they are ready to be interrupted.

We may want to attempt to research a suitable replacement for this system in the future (such as `asyncio` or another such framework), but for now we will keep the older system for compatibility as we get through the python re-write.

A/C: Event handler and synchronization object have been converted to new python module.

**Comment by jghibiki** [comment]
By saying "keep the older system for compatibility" does that mean the initial rewrite will use threads?

**Comment by dekarrin** [comment]
@jghibiki yes, we are currently planning on staying with just plain ol' python threading, the GIL-limited one.

That said, if you were interested in presenting an alternative solution, I'd sure be interested in hearing it.
