### ISSUE TITLE
Convert output module to python

### ISSUE THREAD

**Issue by dekarrin** [moe-serifu-circle/moe-serifu-agent#53]
Output module is a series of functions for delivering output information to the installed devices in a device-agnostic encapsulated way. Output devices will take the information and use the metadata they can while ignoring metadata that is not relevant.

A/C: Output module accepted into python codebase, and has feature parity with original C++ module. Output module is able to write to a TTY via stdout.

**Comment by jghibiki** [comment]
Closing as this issue no longer seems relevant.
